const ListingsActionTypes = {
    ADDING_LISTING_START: 'ADDING_LISTING_START',
    ADDING_LISTING_SUCCESS: 'ADDING_LISTING_SUCCESS',
    ADDING_LISTING_FAILURE: 'ADDING_LISTING_FAILURE',
    GET_LISTINGS_START: 'GET_LISTINGS_START',
    GET_LISTINGS_FAILURE: 'GET_LISTINGS_FAILURE',
    GET_AGENT_LISTINGS_SUCCESS: 'GET_AGENT_LISTINGS_SUCCESS',
    SEARCH_LISTINGS: 'SEARCH_LISTINGS',
    SEARCH_LISTINGS_SUCCESS: 'SEARCH_LISTINGS_SUCCES',
    SET_LOADING_STATE: 'SET_LOADING_STATE'
}

export default ListingsActionTypes